apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ci-cd-app
spec:
  replicas: 2
  selector:
    mactchLabels:
      app: my-ci-cd-app
  template:
    metadata:
      labels:
        app: my-ci-cd-app
    spec:
      containers:
      - name: my-ci-cd-app
        image: 111111111111.dkr.ecr.us-east-2.amazonaws.com/cipipeline:24
        ports: 
        - containerPort: 80
